### ISSUE TITLE
Add GeoJSON(-LD)

### ISSUE THREAD

**Issue by Sveino** [Sveino/Nordic44#1]
Investigate the possibility to use GeoJSON(-LD) as a replacement for GeographicalLocationProfile described in IEC 61968-13:2021.

We would to use JSON-LD since this could be the first step to create IEC 61970-553 that describe how JSON-LD should be used for exchanging RDFS based profiles (IEC 61970-450-series and IEC 61968-13).

We would also like to be complaint with the latest version of GeoSparql v1.1:
https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html
Relevant issue: https://github.com/opengeospatial/ogc-geosparql/issues/1
https://www.ogc.org/standards/geosparql

Best practice: https://www.w3.org/TR/sdw-bp/

JSON-LD 1.1: https://www.w3.org/TR/json-ld11/
JSON-LD test site:
https://json-ld.org/playground/

 The GeoJSON Format: https://datatracker.ietf.org/doc/rfc7946/
A Uniform Resource Identifier for Geographic Locations ('geo' URI): https://datatracker.ietf.org/doc/html/rfc5870

Schema.org: https://schema.org/GeospatialGeometry

Header information should be based on Data Catalog Vocabulary (DCAT) - Version 3: https://www.w3.org/TR/vocab-dcat-3/

Map test site:
https://azuremapscodesamples.azurewebsites.us/?sample=Drag%20and%20Drop%20GeoJSON%20File%20onto%20Map
http://[geojson.io](http://geojson.io/#map=2/20.0/0.0)/#map=2/20.0/0.0

Relevant examples:
https://docs.ogc.org/is/17-003r2/17-003r2.html

GraphDB:
https://graphdb.ontotext.com/documentation/10.0/geo-spatial-extensions.html

**Comment by VladimirAlexiev** [comment]
- This is not conformant to GeoSPARQL, see #11 and https://github.com/opengeospatial/ogc-geosparql/issues/1#issuecomment-1221587143
- Look at https://graphdb.ontotext.com/documentation/10.0/geosparql-support.html not https://graphdb.ontotext.com/documentation/10.0/geo-spatial-extensions.html (which are older and much less powerful)
- GraphDB doesn't support GeoJSON. Please use WKT.

**Comment by Sveino** [comment]
> * GraphDB doesn't support GeoJSON. Please use WKT.

I am not sure how much WKT is used in the Geospartial comunity. The thiniking is that the GeoJSON data is generated from a GIS. Until GraphDB support GeoJSON, I do not see a big issue in converting the GeoJSON to WKT.

**Comment by VladimirAlexiev** [comment]
@Sveino
> I am not sure how much WKT is used in the Geospartial comunity. 

Is this comment based on some observations?

Here are some facts:
- WKT and GML are the only serializations in GeoSPARQL 1.0, so all semantic repositories that support GeoSPARQL, support those.
- GeoSPARQL 1.1 supports 5 serializations, see https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geometry_serializations. But I don't know which semantic repos support GeoSPARQL 1.1, do you?
- GeoJSON doesn't support SRS/CRS, only a fixed one: https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#req_geometry_extension_geojson-literal-srs

**Comment by VladimirAlexiev** [comment]
Hi @Sveino!
- We're now playing with geo data (for checking urban planning regulations) and playing with GML literals.
- This is also related to CityGML (which uses GML) and CityJSON (which uses JSON). GeoSPARQL 1.1 supports a GeoJSON serialization, and I posted  https://github.com/w3c/json-ld-syntax/issues/425
